{
    'name': 'NCF República Dominicana',
    'version': '16.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Genera Número de Comprobante Fiscal para República Dominicana - Proyecto RENACE',
    'author': 'Adderly Marte',
    'website': 'https://renace.tech',
    'license': 'LGPL-3',
    'support': 'adderlymarte@renace.tech',
    'depends': ['account'],
    'data': [
        'security/ir.model.access.csv',
        'views/ncf_fiscal_type_views.xml',
        'views/account_move_views.xml',
        'views/ncf_sequence_views.xml',
        'views/res_config_settings_views.xml',
        'reports/invoice_report.xml',
        'data/fiscal_type_data.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}